import { Router } from "express";
import { db } from "../services/database";
import { canAccessCase } from "../middleware/access";

const router = Router();
const severity = [{ name: "Normal", color: "#22c55e" }, { name: "Mild", color: "#eab308" }, { name: "Moderate", color: "#f97316" }, { name: "Severe", color: "#ef4444" }];
async function scoped(user: any) { const cases = await db.case.findMany({ include: { files: true, reports: true } }); return cases.filter((item) => canAccessCase(user, item)); }
router.get("/overview", async (req: any, res) => { const cases = await scoped(req.user); const ids = cases.map((item) => item.id); const tasks = ids.length ? await db.analysisTask.findMany({ where: { caseId: { in: ids } } }) : []; const reports = cases.flatMap((item) => item.reports); const count = (name: string) => reports.filter((report) => report.severity === name).length; const avg = reports.length ? reports.reduce((total, report) => total + report.cobbAngle, 0) / reports.length : 0; res.json({ success: true, data: { cases: { total: cases.length, male: cases.filter((item) => /male|男/i.test(item.gender)).length, female: cases.filter((item) => /female|女/i.test(item.gender)).length }, files: { total: cases.reduce((total, item) => total + item.files.length, 0) }, reports: { total: reports.length, completed: reports.filter((report) => report.annotationStatus === "approved").length }, aisDistribution: { normal: count("Normal"), mild: count("Mild"), moderate: count("Moderate"), severe: count("Severe") }, tasks: { total: tasks.length, success: tasks.filter((task) => task.status === "success").length, failed: tasks.filter((task) => task.status === "failed").length, successRate: tasks.length ? (tasks.filter((task) => task.status === "success").length * 100 / tasks.length).toFixed(1) : "0" }, metrics: { avgCobbAngle: avg.toFixed(1), positiveRate: reports.length ? (reports.filter((report) => report.severity !== "Normal").length * 100 / reports.length).toFixed(1) : "0" } } }); });
router.get("/cases-distribution", async (req: any, res) => { const field = req.query.type === "doctor" ? "doctor" : req.query.type === "gender" ? "gender" : "department"; const distribution: Record<string, number> = {}; for (const item of await scoped(req.user)) { const value = String(item[field] || "Unspecified"); distribution[value] = (distribution[value] || 0) + 1; } res.json({ success: true, data: Object.entries(distribution).map(([name, value]) => ({ name, value })) }); });
router.get("/ais-distribution", async (req: any, res) => { const reports = (await scoped(req.user)).flatMap((item) => item.reports); res.json({ success: true, data: severity.map((item) => ({ ...item, value: reports.filter((report) => report.severity === item.name).length })) }); });
router.get("/time-series", async (req: any, res) => { const metric = req.query.metric; const cases = await scoped(req.user); const caseIds = cases.map((item) => item.id); const rows = metric === "analyses" ? (caseIds.length ? await db.analysisTask.findMany({ where: { caseId: { in: caseIds } } }) : []) : metric === "reports" ? cases.flatMap((item) => item.reports) : cases; const values = new Map<string, number>(); for (const row of rows as any[]) { const date = row.createdAt.toISOString().slice(0, 10); values.set(date, (values.get(date) || 0) + 1); } res.json({ success: true, data: [...values.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([date, value]) => ({ date, value })) }); });
router.post("/export", async (req: any, res) => { const cases = await scoped(req.user); const reports = cases.flatMap((item) => item.reports); const body = [["指标", "数值"], ["病例数", cases.length], ["扫描文件数", cases.reduce((sum, item) => sum + item.files.length, 0)], ["报告数", reports.length], ["正常", reports.filter((item) => item.severity === "Normal").length], ["轻度", reports.filter((item) => item.severity === "Mild").length], ["中度", reports.filter((item) => item.severity === "Moderate").length], ["重度", reports.filter((item) => item.severity === "Severe").length]].map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\r\n"); res.setHeader("Content-Type", "text/csv; charset=utf-8"); res.setHeader("Content-Disposition", 'attachment; filename="AIS-statistics.csv"'); return res.send(`\uFEFF${body}`); });
export default router;
