import bcrypt from "bcryptjs";
import { Router } from "express";
import { db, audit } from "../services/database";
import { requireRoles } from "../middleware/access";

const router = Router();
const present = (user: any) => ({ id: user.id, username: user.username, name: user.displayName, role: user.role, department: user.department, institutionId: user.institutionId, email: user.email, phone: user.phone, status: user.active ? "active" : "disabled", createdAt: user.createdAt });
const visible = (actor: any, user: any) => actor.role === "system_admin" || (Boolean(actor.institutionId) && actor.institutionId === user.institutionId);
const normalizeUsername = (value: unknown) => { const username = String(value ?? "").trim(); return username.length >= 2 && username.length <= 32 && /^[\p{L}\p{N}._-]+$/u.test(username) ? username : null; };
const usernameError = "用户名需为 2-32 位字母、数字或 . _ -，且不能包含空格。";

router.get("/", requireRoles("system_admin", "institution_admin"), async (req: any, res) => { let users = await db.user.findMany({ orderBy: { createdAt: "desc" } }); users = users.filter((user) => visible(req.user, user)); if (typeof req.query.keyword === "string") users = users.filter((user) => user.username.includes(req.query.keyword) || user.displayName.includes(req.query.keyword)); if (typeof req.query.role === "string") users = users.filter((user) => user.role === req.query.role); const page = Math.max(1, Number(req.query.page || 1)); const pageSize = Math.min(100, Math.max(1, Number(req.query.pageSize || 20))); res.json({ success: true, data: { list: users.slice((page - 1) * pageSize, page * pageSize).map(present), total: users.length, page, pageSize } }); });
router.get("/:id", requireRoles("system_admin", "institution_admin"), async (req: any, res) => { const user = await db.user.findUnique({ where: { id: req.params.id } }); if (!user || !visible(req.user, user)) return res.status(404).json({ success: false, message: "User not found." }); res.json({ success: true, data: present(user) }); });
router.post("/", requireRoles("system_admin", "institution_admin"), async (req: any, res) => { const rawUsername = req.body?.username ? normalizeUsername(req.body.username) : null; if (req.body?.username && !rawUsername) return res.status(400).json({ success: false, message: usernameError }); const username = rawUsername || `operator_${Date.now()}`; const password = String(req.body?.password || ""); const institutionId = req.user.role === "system_admin" && typeof req.body?.institutionId === "string" ? req.body.institutionId : req.user.institutionId; if (!institutionId) return res.status(400).json({ success: false, message: "Institution is required." }); if (password.length < 12) return res.status(400).json({ success: false, message: "Password must contain at least 12 characters." }); const role = req.user.role === "institution_admin" ? "operator" : String(req.body?.role || "operator"); if (!["system_admin", "institution_admin", "operator"].includes(role)) return res.status(400).json({ success: false, message: "无效的角色。" }); try { const user = await db.user.create({ data: { username, passwordHash: await bcrypt.hash(password, 12), displayName: String(req.body?.name || username), role, institutionId, department: req.body?.department, email: req.body?.email, phone: req.body?.phone } }); await audit(req.user.id, "create", "User", user.id); res.status(201).json({ success: true, data: present(user) }); } catch { res.status(409).json({ success: false, message: "用户名已存在，请换一个。" }); } });
router.put("/:id", requireRoles("system_admin", "institution_admin"), async (req: any, res) => { const existing = await db.user.findUnique({ where: { id: req.params.id } }); if (!existing || !visible(req.user, existing)) return res.status(404).json({ success: false, message: "User not found." }); const data: any = { displayName: req.body?.name, role: req.user.role === "system_admin" ? req.body?.role : undefined, institutionId: req.user.role === "system_admin" ? req.body?.institutionId : undefined, department: req.body?.department, email: req.body?.email, phone: req.body?.phone, active: req.body?.status ? req.body.status === "active" : undefined }; if (req.body?.username !== undefined) { const username = normalizeUsername(req.body.username); if (!username) return res.status(400).json({ success: false, message: usernameError }); data.username = username; } if (typeof req.body?.password === "string" && req.body.password !== "") { if (req.body.password.length < 12) return res.status(400).json({ success: false, message: "密码至少需要 12 位。" }); data.passwordHash = await bcrypt.hash(req.body.password, 12); } try { const user = await db.user.update({ where: { id: existing.id }, data }); await audit(req.user.id, "update", "User", user.id); res.json({ success: true, data: present(user) }); } catch { res.status(409).json({ success: false, message: "用户名已存在，请换一个。" }); } });
router.delete("/:id", requireRoles("system_admin"), async (req: any, res) => { if (req.params.id === req.user.id) return res.status(400).json({ success: false, message: "Cannot delete the current user." }); const user = await db.user.findUnique({ where: { id: req.params.id } }); if (!user) return res.status(404).json({ success: false, message: "User not found." }); const ownedCases = await db.case.count({ where: { ownerId: user.id } }); if (ownedCases > 0) return res.status(400).json({ success: false, message: "该用户名下还有受检者档案，请先转移或删除后再删除用户。" }); await db.$transaction(async (tx) => { await tx.analysisTask.deleteMany({ where: { submittedById: user.id } }); await tx.user.delete({ where: { id: user.id } }); }); await audit(req.user.id, "delete", "User", user.id); res.json({ success: true }); });
router.post("/:id/toggle-status", requireRoles("system_admin"), async (req: any, res) => { const user = await db.user.findUnique({ where: { id: req.params.id } }); if (!user) return res.status(404).json({ success: false, message: "User not found." }); const updated = await db.user.update({ where: { id: user.id }, data: { active: !user.active } }); res.json({ success: true, data: { status: updated.active ? "active" : "disabled" } }); });
export default router;
