import { useEffect, useMemo, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { LoaderCircle, Play, RefreshCw } from "lucide-react";
import Header from "@/components/layout/Header";
import Sidebar from "@/components/layout/Sidebar";
import api from "@/lib/api";

type CaseItem = { id: string; caseNumber: string; name: string; gender: string; height?: number; weight?: number; fileCount?: number };
type Task = { id: string; status: string; progress: number; failureReason?: string; resultJson?: string };
const labels: Record<string, string> = { pending: "Waiting", running: "Analyzing", success: "Complete", failed: "Failed", cancelled: "Cancelled" };

export default function Analysis() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const [cases, setCases] = useState<CaseItem[]>([]); const [selected, setSelected] = useState<string[]>([]); const [tasks, setTasks] = useState<Task[]>([]); const [loading, setLoading] = useState(false); const [message, setMessage] = useState("");
  const isAdmin = localStorage.getItem("user_role") === "system_admin" || localStorage.getItem("user_role") === "admin";
  const load = async () => { const result = await api.getCases({ pageSize: 100 }); const list = result.list || result.data?.list || []; setCases(list); const target = params.get("id"); if (target && list.some((item: CaseItem) => item.id === target)) setSelected([target]); };
  useEffect(() => { void load().catch((error) => setMessage(error.message)); }, []);
  useEffect(() => { if (!tasks.some((task) => task.status === "pending" || task.status === "running")) return; const timer = window.setInterval(() => { void Promise.all(tasks.map((task) => api.getTask(task.id).catch(() => task))).then((next) => setTasks(next)); }, 1500); return () => window.clearInterval(timer); }, [tasks]);
  const eligible = useMemo(() => cases.filter((item) => selected.includes(item.id) && item.fileCount && item.height && item.weight && item.gender), [cases, selected]);
  const submit = async (batch: boolean) => { if (!eligible.length) return setMessage("Select a case with clinical data and an uploaded PLY scan."); setLoading(true); setMessage(""); try { if (batch) { const result = await api.analyzeBatch(eligible.map((item) => item.id)); const queued = result.tasks || result.data?.tasks || []; setTasks((old) => [...queued, ...old]); const skipped = result.skipped || result.data?.skipped || []; if (skipped.length) setMessage(`${skipped.length} case(s) were skipped.`); } else { const task = await api.analyzeSingle(eligible[0].id); setTasks((old) => [task, ...old]); } } catch (error: any) { setMessage(error.message || "Unable to queue analysis."); } finally { setLoading(false); } };
  return <div className="layout-main"><Sidebar isAdmin={isAdmin} /><div className="layout-header"><Header isAdmin={isAdmin} /></div><main className="layout-content space-y-5"><div className="flex items-center justify-between gap-4"><div><h1 className="text-page-title">AIS Analysis</h1><p className="text-body mt-1">Submit uploaded PLY scans to the local AIS algorithm.</p></div><button className="btn-icon" title="Refresh cases" onClick={() => void load()}><RefreshCw size={18} /></button></div>{message && <div className="rounded border border-amber-300 bg-amber-50 px-3 py-2 text-sm text-amber-900">{message}</div>}<section className="space-y-3"><div className="flex gap-2"><button className="btn-primary inline-flex items-center gap-2" disabled={loading || eligible.length !== 1} onClick={() => void submit(false)}>{loading ? <LoaderCircle className="animate-spin" size={16} /> : <Play size={16} />}Analyze selected</button><button className="btn-secondary" disabled={loading || !eligible.length} onClick={() => void submit(true)}>Analyze selected batch</button></div><div className="overflow-x-auto border border-[color:var(--color-border)]"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3"></th><th className="p-3">Case</th><th className="p-3">Sex</th><th className="p-3">Scan</th><th className="p-3">Ready</th></tr></thead><tbody>{cases.map((item) => { const ready = Boolean(item.fileCount && item.height && item.weight && item.gender); return <tr key={item.id} className="border-b"><td className="p-3"><input type="checkbox" checked={selected.includes(item.id)} disabled={!ready} onChange={() => setSelected((old) => old.includes(item.id) ? old.filter((id) => id !== item.id) : [...old, item.id])} /></td><td className="p-3">{item.caseNumber} {item.name}</td><td className="p-3">{item.gender}</td><td className="p-3">{item.fileCount || 0}</td><td className="p-3">{ready ? "Ready" : "Clinical data or PLY scan required"}</td></tr>; })}</tbody></table></div></section>{tasks.length > 0 && <section><h2 className="text-card-title mb-3">Local tasks</h2><div className="space-y-2">{tasks.map((task) => <div key={task.id} className="flex items-center justify-between border border-[color:var(--color-border)] px-3 py-2"><span className="font-mono text-xs">{task.id}</span><span>{labels[task.status] || task.status} {task.progress}%</span>{task.status === "success" && <button className="btn-link" onClick={() => navigate("/reports")}>View reports</button>}{task.failureReason && <span className="text-red-600">{task.failureReason}</span>}</div>)}</div></section>}</main></div>;
}
