import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { BarChart3, ClipboardPlus, FileUp, Search, Users, ShieldCheck } from "lucide-react";
import Header from "@/components/layout/Header";
import Sidebar from "@/components/layout/Sidebar";
import api from "@/lib/api";

type Stats = { total: number; pendingUpload: number; pendingAnalysis: number; completed: number; withReports: number };
const adminRoles = ["admin", "system_admin", "institution_admin"];
export default function Dashboard() {
  const navigate = useNavigate(); const [stats, setStats] = useState<Stats | null>(null); const [loading, setLoading] = useState(true); const role = localStorage.getItem("user_role") || "operator"; const isAdmin = adminRoles.includes(role);
  useEffect(() => { api.getCaseStats().then(setStats).catch(() => setStats(null)).finally(() => setLoading(false)); }, []);
  const cards = useMemo(() => [{ label: "受检者总量", value: stats?.total, icon: Users, tone: "blue" }, { label: "待分析", value: stats?.pendingAnalysis, icon: Search, tone: "amber" }, { label: "已完成分析", value: stats?.completed, icon: BarChart3, tone: "green" }, { label: "待上传文件", value: stats?.pendingUpload, icon: FileUp, tone: "violet" }], [stats]);
  const actions = [{ title: "新建受检者", description: "录入基本档案信息", icon: ClipboardPlus, onClick: () => navigate("/case-record") }, { title: "受检者管理", description: "查询、筛选和查看详情", icon: Users, onClick: () => navigate("/cases") }, { title: "数据统计", description: "查看系统数据概览", icon: BarChart3, onClick: () => navigate("/statistics") }];
  if (isAdmin) actions.push({ title: "用户管理", description: "管理账号和权限", icon: ShieldCheck, onClick: () => navigate("/admin/users") });
  return <div className="layout-main"><Sidebar isAdmin={isAdmin}/><div className="layout-header"><Header isAdmin={isAdmin}/></div><div className="layout-content"><div className="content-wrapper space-y-8"><div><p className="text-helper uppercase tracking-wider text-[color:var(--color-primary)] mb-2">Overview</p><h1 className="text-page-title">工作台</h1><p className="text-body mt-2">查看当前筛查任务、报告和系统工作状态。</p></div><section><div className="flex items-center justify-between mb-4"><h2 className="text-card-title">数据概览</h2><span className="text-helper">数据实时来自本地 SQLite 数据库</span></div><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">{cards.map(({label,value,icon:Icon,tone}) => <Metric key={label} label={label} value={loading ? "—" : String(value ?? 0)} icon={<Icon size={20}/>} tone={tone}/>)}</div></section><section><h2 className="text-card-title mb-4">快捷操作</h2><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">{actions.map(({title,description,icon:Icon,onClick}) => <button key={title} onClick={onClick} className="card-base p-5 text-left hover:-translate-y-0.5 hover:shadow-lg transition-all cursor-pointer"><span className="inline-flex w-10 h-10 items-center justify-center rounded-lg bg-[color:var(--color-primary-light)] text-[color:var(--color-primary)] mb-4"><Icon size={20}/></span><h3 className="text-card-title">{title}</h3><p className="text-helper mt-1">{description}</p></button>)}</div></section></div></div></div>;
}
function Metric({ label, value, icon, tone }: { label: string; value: string; icon: React.ReactNode; tone: string }) { const tones: Record<string,string> = { blue: "bg-blue-50 text-blue-700", amber: "bg-amber-50 text-amber-700", green: "bg-emerald-50 text-emerald-700", violet: "bg-violet-50 text-violet-700" }; return <div className="card-base p-5"><div className="flex items-start justify-between"><p className="text-helper">{label}</p><span className={`inline-flex w-9 h-9 items-center justify-center rounded-lg ${tones[tone]}`}>{icon}</span></div><p className="text-data-lg mt-5 text-[color:var(--color-text-primary)]">{value}</p></div>; }
