import { useEffect, useState } from "react";
import { DatabaseBackup, RefreshCw } from "lucide-react";
import Header from "@/components/layout/Header";
import Sidebar from "@/components/layout/Sidebar";
import api from "@/lib/api";

type Backup = { name: string; sizeBytes: number };
export default function AdminSettings() {
  const [name, setName] = useState("AIS"); const [timezone, setTimezone] = useState("Asia/Shanghai"); const [backups, setBackups] = useState<Backup[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const loadBackups = async () => { try { const result = await api.getBackups(); setBackups(result.list || result.data?.list || []); } catch (error: any) { setMessage(error.message); } };
  const loadSettings = async () => { try { const result = await api.getSettings(); const system = result.system || result.data?.system || result; setName(system.name || "AIS"); setTimezone(system.timezone || "Asia/Shanghai"); } catch (error: any) { setMessage(error.message); } };
  const saveSettings = async () => { setBusy(true); try { await api.updateSettings("system", { name, timezone }); setMessage("应用设置已保存到本地数据库。"); } catch (error: any) { setMessage(error.message); } finally { setBusy(false); } };
  useEffect(() => { void Promise.all([loadBackups(), loadSettings()]); }, []);
  const backup = async () => { setBusy(true); try { const result = await api.createBackup(); setMessage(`Backup created: ${result.name || result.data?.name}`); await loadBackups(); } catch (error: any) { setMessage(error.message); } finally { setBusy(false); } };
  const restore = async (item: Backup) => { if (!window.confirm(`Restore ${item.name}? The application will apply it on next restart.`)) return; setBusy(true); try { await api.restoreBackup(item.name); setMessage("Restore has been validated and will be applied on the next application restart."); } catch (error: any) { setMessage(error.message); } finally { setBusy(false); } };
  return <div className="layout-main"><Sidebar isAdmin /><div className="layout-header"><Header isAdmin /></div><main className="layout-content"><div className="content-wrapper space-y-6"><div><h1 className="text-page-title">系统设置</h1><p className="text-body text-[color:var(--color-text-secondary)]">本地应用配置与受保护数据备份。</p></div>{message && <div className="border border-[color:var(--color-border)] px-4 py-3 text-sm">{message}</div>}<section className="card-base p-6"><h2 className="text-card-title mb-4">应用配置</h2><div className="grid max-w-xl gap-3"><label className="text-sm">名称<input className="input-base mt-1 w-full" value={name} onChange={(event) => setName(event.target.value)} /></label><label className="text-sm">时区<input className="input-base mt-1 w-full" value={timezone} onChange={(event) => setTimezone(event.target.value)} /></label><button className="btn-primary w-fit" disabled={busy} onClick={() => void saveSettings()}>保存设置</button></div></section><section className="card-base p-6"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="text-card-title">本地备份</h2><p className="text-helper mt-1">备份包含 SQLite、扫描文件、算法结果与标注真值。</p></div><div className="flex gap-2"><button className="btn-icon" title="刷新备份" onClick={() => void loadBackups()}><RefreshCw size={17} /></button><button className="btn-primary inline-flex items-center gap-2" disabled={busy} onClick={() => void backup()}><DatabaseBackup size={16} />创建备份</button></div></div><div className="space-y-2">{backups.length === 0 && <p className="text-helper">暂无本地备份。</p>}{backups.map((item) => <div key={item.name} className="flex items-center justify-between border border-[color:var(--color-border)] px-3 py-2"><span className="font-mono text-xs break-all">{item.name}</span><div className="ml-3 flex shrink-0 items-center gap-3"><span className="text-helper">{(item.sizeBytes / 1024 / 1024).toFixed(1)} MB</span><button className="btn-secondary" disabled={busy} onClick={() => void restore(item)}>恢复</button></div></div>)}</div></section></div></main></div>;
}
