import { useEffect, useState } from "react";
import { DatabaseBackup, RefreshCw } from "lucide-react";
import { useTranslation } from "react-i18next";
import Header from "@/components/layout/Header";
import Sidebar from "@/components/layout/Sidebar";
import { confirmDialog } from "@/components/ConfirmDialog";
import api from "@/lib/api";

type Backup = { name: string; sizeBytes: number };
export default function AdminSettings() {
  const { t } = useTranslation();
  const [name, setName] = useState("AIS"); const [timezone, setTimezone] = useState("Asia/Shanghai"); const [backups, setBackups] = useState<Backup[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const loadBackups = async () => { try { const result = await api.getBackups(); setBackups(result.list || result.data?.list || []); } catch (error: any) { setMessage(error.message); } };
  const loadSettings = async () => { try { const result = await api.getSettings(); const system = result.system || result.data?.system || result; setName(system.name || "AIS"); setTimezone(system.timezone || "Asia/Shanghai"); } catch (error: any) { setMessage(error.message); } };
  const saveSettings = async () => { setBusy(true); try { await api.updateSettings("system", { name, timezone }); setMessage(t("adminSettings.saved")); } catch (error: any) { setMessage(error.message); } finally { setBusy(false); } };
  useEffect(() => { void Promise.all([loadBackups(), loadSettings()]); }, []);
  const backup = async () => { setBusy(true); try { const result = await api.createBackup(); setMessage(t("adminSettings.backupCreated", { name: result.name || result.data?.name })); await loadBackups(); } catch (error: any) { setMessage(error.message); } finally { setBusy(false); } };
  const restore = async (item: Backup) => { if (!(await confirmDialog(t("adminSettings.restoreConfirm", { name: item.name }), { destructive: true }))) return; setBusy(true); try { await api.restoreBackup(item.name); setMessage(t("adminSettings.restoreApplied")); } catch (error: any) { setMessage(error.message); } finally { setBusy(false); } };
  return <div className="layout-main"><Sidebar isAdmin /><div className="layout-header"><Header isAdmin /></div><main className="layout-content"><div className="content-wrapper space-y-6"><div><h1 className="text-3xl font-semibold tracking-tight text-foreground">{t("adminSettings.title")}</h1><p className="text-sm text-[color:var(--color-text-secondary)]">{t("adminSettings.subtitle")}</p></div>{message && <div className="border border-[color:var(--color-border)] px-4 py-3 text-sm">{message}</div>}<section className="card-base p-6"><h2 className="text-lg font-semibold text-foreground mb-4">{t("adminSettings.appConfig")}</h2><div className="grid max-w-xl gap-3"><label className="text-sm">{t("adminSettings.name")}<input className="input-base mt-1 w-full" value={name} onChange={(event) => setName(event.target.value)} /></label><label className="text-sm">{t("adminSettings.timezone")}<input className="input-base mt-1 w-full" value={timezone} onChange={(event) => setTimezone(event.target.value)} /></label><button className="btn-primary w-fit" disabled={busy} onClick={() => void saveSettings()}>{t("adminSettings.saveSettings")}</button></div></section><section className="card-base p-6"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="text-lg font-semibold text-foreground">{t("adminSettings.localBackup")}</h2><p className="text-sm text-muted-foreground mt-1">{t("adminSettings.backupHint")}</p></div><div className="flex gap-2"><button className="btn-icon" title={t("adminSettings.refreshBackup")} onClick={() => void loadBackups()}><RefreshCw size={17} /></button><button className="btn-primary inline-flex items-center gap-2" disabled={busy} onClick={() => void backup()}><DatabaseBackup size={16} />{t("adminSettings.createBackup")}</button></div></div><div className="space-y-2">{backups.length === 0 && <p className="text-sm text-muted-foreground">{t("adminSettings.backupEmpty")}</p>}{backups.map((item) => <div key={item.name} className="flex items-center justify-between border border-[color:var(--color-border)] px-3 py-2"><span className="font-mono text-xs break-all">{item.name}</span><div className="ml-3 flex shrink-0 items-center gap-3"><span className="text-sm text-muted-foreground">{(item.sizeBytes / 1024 / 1024).toFixed(1)} MB</span><button className="btn-secondary" disabled={busy} onClick={() => void restore(item)}>{t("adminSettings.restore")}</button></div></div>)}</div></section></div></main></div>;
}
