import { useLocation, useNavigate } from "react-router-dom";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";

const items = [{ path: "/dashboard", label: "工作台" }, { path: "/cases", label: "受检者管理" }, { path: "/statistics", label: "数据统计" }];
export default function Header({ isAdmin }: { isAdmin: boolean }) {
  const navigate = useNavigate(); const location = useLocation(); const role = localStorage.getItem("user_role"); const isSystemAdmin = role === "system_admin";
  const logout = () => { localStorage.removeItem("user_role"); navigate("/login"); };
  return <div className="w-full h-full px-4 md:px-6 flex items-center gap-3 md:gap-6"><div className="shrink-0 flex items-center gap-2"><div className="w-8 h-8 bg-[color:var(--color-primary)] rounded-md flex items-center justify-center text-white font-bold text-sm">AIS</div><div className="text-card-title text-[color:var(--color-text-primary)] font-semibold whitespace-nowrap">AIS 筛查系统</div></div><nav className="min-w-0 flex-1 overflow-x-auto"><div className="flex items-center gap-2 w-full min-w-[520px] pr-3">{items.map(item => <div key={item.path} className="flex-1 px-2"><button onClick={() => navigate(item.path)} className={`block w-1/2 min-w-[90px] mx-auto px-2 py-2 rounded-btn text-body font-semibold transition-colors whitespace-nowrap text-center ${location.pathname === item.path ? "bg-[color:var(--color-primary-light)] text-[color:var(--color-primary)]" : "text-[color:var(--color-text-secondary)] hover:bg-[color:var(--color-neutral)]"}`}>{item.label}</button></div>)}</div></nav><div className="ml-auto shrink-0 flex items-center gap-3 pl-3 md:pl-4 border-l border-[color:var(--color-border)]"><DropdownMenu><DropdownMenuTrigger asChild><button className="flex items-center gap-3 hover:bg-[color:var(--color-neutral)] rounded-btn px-2 py-1.5 transition-colors"><div className="text-right hidden md:block"><p className="text-body font-semibold text-[color:var(--color-text-primary)]">{isAdmin ? "管理员" : "临床操作员"}</p><p className="text-helper text-[color:var(--color-text-tertiary)]">{isAdmin ? "骨科" : "脊柱外科"}</p></div><div className="w-9 h-9 rounded-full bg-[color:var(--color-primary)] flex items-center justify-center text-white font-semibold">{isAdmin ? "A" : "C"}</div></button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-44"><DropdownMenuItem onClick={() => navigate("/settings")}>个人设置</DropdownMenuItem>{(isSystemAdmin || role === "institution_admin") && <>{isSystemAdmin && <DropdownMenuItem onClick={() => navigate("/admin/settings")}>系统设置</DropdownMenuItem>}<DropdownMenuItem onClick={() => navigate("/admin/users")}>用户管理</DropdownMenuItem></>}<DropdownMenuSeparator/><DropdownMenuItem onClick={logout} className="text-[color:var(--color-error)] focus:text-[color:var(--color-error)]">退出登录</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></div>;
}
